### PR TITLE
Create a serial queue for each Websocket's callbacks.

### PR DESCRIPTION
**Pull request by bridger**
This addresses https://github.com/IBM-Swift/Kitura-WebSocket/issues/6.

I have been able to reproduce this bug. On connect I have a client send many messages one after another. Each one requires a small amount of processing, such as appending to an array. The callback looked something like this:

```
func received(message: Data, from connection: WebSocketConnection) {
    if let deserializedMessage = try? ClientToServerMessage(serializedData: message) {
        // modelQueue is a serial queue for controlling access to the model
        modelQueue.async {
            receivedMessages.append(deserializedMessage)
        }
    }
}
```

Sure enough the `receivedMessages` array had messages from the same client in an unpredictable order. With the fixes from this branch the messages from one client are consistently in the right order.

I also set breakpoints to see which threads the callbacks were being called on. Two different clients connected and sending messages ended up with their messages each coming in concurrently on two threads. This confirms a server is still able to handle multiple clients concurrently.

### CODE REVIEW

**Comment by shmuelk** [comment]
The problem with using a private serial queue is that there is limited number of threads on macOS (64 I believe) and as such there is a limit to the number of serial queues that can be created.

Thus using serial queues for serialization here, will limit the scaleability of Kitura-WebSocket.

I'm about to work on a different solution.

**Comment by shmuelk** [comment]
I have spoken with a libdispatch expert in IBM and I seem to have been mistaken.

**Comment by shmuelk** [comment]
Before I can merge this you need to sign a CLA.

Please see our [CLA repo](http://github.com/IBM-Swift/CLA) for more information.

**Comment by bridger** [comment]
Thanks for checking that @shmuelk.

I just sent in my CLA. I've had a great time using Kitura and I'm excited to contribute.

**Comment by shmuelk** [comment]
Travis-CI failed for Swift 3.1 which has a memory corruption in Foundation in an API that Kitura-WebSocket uses. The tests ran on Swift 3.0.2 on Linux and on Swift 3.1 on macOS. I'm merging.

**Pull request merged**
