### PR TITLE
Switch to KituraNIO if environment variable is set.

### PR DESCRIPTION
**Pull request by mamabusi**

### CODE REVIEW

**Comment by pushkarnk** [comment]
@mamabusi I don't think this switch would work with Kitura-WebSocket for two reasons. Firstly, Kitura-WebSocket uses some KituraNet classes, like IncomingSocketProcessor,  that do not have an equivalent in Kitura-NIO. Secondly, it also uses BlueSocket extensively, which is pulled via KituraNet. In the SwiftNIO port of WebSocket, we use NIO's abstractions.

**Comment by mamabusi** [comment]
Had a discussion with @pushkarnk and @nethraravindran . The switch to KituraNIO would not work here because of missing API of BlueSocket like the `IncomingSocketHandler`. Closing the PR.

**Comment by djones6** [comment]
@pushkarnk @mamabusi So what's the solution here? Could we merge the `websocket-nio` and `master` branches together, or potentially cut a special tag of WebSocket which we use in NIO mode?

**Comment by mamabusi** [comment]
@djones6  We were able to use .exact() with a tag to point NIO mode of Websocket.

**Pull request closed without merging**
